export const QUESTIONS = 'QUESTIONS';
export const CURRENT_QUESTION = 'CURRENT_QUESTION';
export const NEXT_QUESTION = 'NEXT_QUESTION'
export const CLEAR_QUESTION = 'CLEAR_QUESTION';
export const SET_TIMER = 'SET_TIMER'